Calendar/ViewModels/NotificationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Calendar.ViewModels
{
    public class NotificationViewModel
    {
        public Guid Id { get; set; }
        [Required]
        public int Hours { get; set; }
        [Required]
        public int Minutes { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "The {0} value cannot exceed {1} characters. ")]
        public string Description { get; set; }
    }
}

Calendar/Pages/Calendar/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using DAL;
using DAL.Entites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Calendar.Pages.Calendar
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public int Year{ get; private set; }
        public int Month{ get; private set; }
        public IEnumerable<DateTime> Calendar { get; private set; }
        public IQueryable<Notification> Notifications { get; private set; }

        public IndexModel(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult OnGet(string year, string month)
        {
            ParseRouteParams(year,month);
            if (year == null || month == null)
            {
                Year = DateTime.Now.Year;
                Month = DateTime.Now.Month;
            }
            else if (Month > 12||Month<1)
            {
                return NotFound();
            }
            Calendar = GetCalendar();
            Notifications = _context.Notifications.Where(n => n.Date.Year.Equals(Year) && n.Date.Month.Equals(Month));
            return Page();
        }

        #region suply methods

        private IEnumerable<DateTime> GetCalendar()
        {
            var days = new List<DateTime>();
            var startMonth = new DateTime(Year, Month, 1);
            var startDayOfWeek = (int)startMonth.DayOfWeek;
            if (startDayOfWeek == 0) { startDayOfWeek = 7; }
            var calendarDays = startMonth.AddDays(1 - startDayOfWeek);
            for (var i=0; i < 42; i++)
            {
                days.Add(calendarDays.AddDays(i));
            }
            return days;
        }
        public string GetMonthName()
        {
            return CultureInfo.GetCultureInfo("en").DateTimeFormat.GetMonthName(Month);
        }
        private void ParseRouteParams(string year, string month)
        {
            var intMonth = Convert.ToInt32(month);
            var intYear = Convert.ToInt32(year);
            Year = intYear;
            Month = intMonth;
        }

        #endregion
    }
}

Calendar/Pages/Calendar/Notification.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Calendar.ViewModels;
using DAL;
using DAL.Entites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Calendar.Pages.Calendar
{
    public class NotificationModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public int Year { get; private set; }
        public int Month { get; private set; }
        public int Day { get; private set; }
        public IEnumerable<DateTime> Calendar { get; private set; }
        public IQueryable<Notification> Notifications;
        public IQueryable<Notification> DayNotifications;

        public NotificationModel(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult OnGet(string year, string month, string day)
        {
            ParseRouteParams(year, month, day);
            if (Year.Equals(0) || Month > 12 || Month < 1 || Day < 1)
            {
                return NotFound();
            }
            Calendar = GetCalendar();
            if (!Calendar.Where(c=>c.Month.Equals(Month)).Select(c => c.Day).Contains(Day))
            {
                Day = Calendar.Where(c=>c.Month.Equals(Month)).Min(d => d.Day);
            }
            Notifications = _context.Notifications.Where(n => n.Date.Year.Equals(Year) && n.Date.Month.Equals(Month));
            DayNotifications = Notifications.Where(n => n.Date.Day.Equals(Day));
            return Page();
        }

        #region Create new notification

        [BindProperty]
        public NotificationViewModel NotificationViewModel { get; set; }
        public async Task<IActionResult> OnPostCreateAsync(string year, string month, string day)
        {
            ParseRouteParams(year, month, day);
            if (Year.Equals(0) || Month > 12 || Month < 1 || Day < 1)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return OnGet(Year.ToString(), Month.ToString(), Day.ToString());
            }
            var notification = new Notification
            {
                Date = new DateTime(Year, Month, Day, NotificationViewModel.Hours, NotificationViewModel.Minutes, 0),
                Description = NotificationViewModel.Description
            };
            await _context.Notifications.AddAsync(notification);
            await _context.SaveChangesAsync();

            return OnGet(Year.ToString(), Month.ToString(), Day.ToString());
        }

        #endregion

        #region Delete notification

        public async Task<IActionResult> OnPostDeleteAsync(Guid notificationId, string year, string month, string day)
        {
            if (Guid.Empty.Equals(notificationId))
            {
                return NotFound();
            }

            var notification = await _context.Notifications.FindAsync(notificationId);

            if (notification != null)
            {
                _context.Notifications.Remove(notification);
                await _context.SaveChangesAsync();
            }

            return OnGet(year, month, day);
        }

        #endregion
        
        #region suply methods

        private IEnumerable<DateTime> GetCalendar()
        {
            var days = new List<DateTime>();
            var startMonth = new DateTime(Year, Month, 1);
            var startDayOfWeek = (int)startMonth.DayOfWeek;
            if (startDayOfWeek == 0) { startDayOfWeek = 7; }
            var calendarDays = startMonth.AddDays(1 - startDayOfWeek);
            for (var i = 0; i < 42; i++)
            {
                days.Add(calendarDays.AddDays(i));
            }
            return days;
        }
        public string GetMonthName()
        {
            return CultureInfo.GetCultureInfo("en").DateTimeFormat.GetMonthName(Month);
        }

        private void ParseRouteParams(string year, string month, string day)
        {
            var intMonth = Convert.ToInt32(month);
            var intYear = Convert.ToInt32(year);
            var intDay = Convert.ToInt32(day);
            Year = intYear;
            Month = intMonth;
            Day = intDay;
        }

        #endregion
    }
}

Calendar/Pages/Calendar/Index.cshtml
@page
@using Microsoft.AspNetCore.Routing
@model IndexModel
@{
    var i = 1;
    int routeLastMonth;
    int routeLastYear;
    if (Model.Month == 1)
    {
        routeLastYear = Model.Year - 1;
        routeLastMonth = 12;
    }
    else
    {
        routeLastMonth = Model.Month - 1;
        routeLastYear = Model.Year;
    }
    int routeNextMonth;
    int routeNextYear;
    if (Model.Month == 12)
    {
        routeNextYear = Model.Year + 1;
        routeNextMonth = 1;
    }
    else
    {
        routeNextMonth = Model.Month + 1;
        routeNextYear = Model.Year;
    }
}
<link rel="stylesheet" href="~/css/calendar/index.css" />
<div class="d-flex justify-content-center">
    <div class="w-50 d-flex flex-column">
        <div class="d-flex justify-content-around mb-2">
            <a asp-route-year="@routeLastYear" asp-route-month="@routeLastMonth"><button type="button" class="btn btn-primary">Last month</button></a>
            <h1>@Model.Year @Model.GetMonthName()</h1>
            <a asp-route-year="@routeNextYear" asp-route-month="@routeNextMonth"><button type="button" class="btn btn-primary">Next month</button></a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Mo</th>
                    <th scope="col" class="text-center">Tu</th>
                    <th scope="col" class="text-center">We</th>
                    <th scope="col" class="text-center">Th</th>
                    <th scope="col" class="text-center">Fr</th>
                    <th scope="col" class="text-center">St</th>
                    <th scope="col" class="text-center">Su</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    @foreach (var date in Model.Calendar)
                    {
                        <td class="text-center">
                            <div class="d-flex justify-content-right" @(date.Month != Model.Month ? "style=color:gray" : "")>
                                <a class="link" asp-page="Notification" asp-route-year="@date.Year" asp-route-month="@date.Month" asp-route-day="@date.Day">
                                    @date.Day
                                </a>
                                @if (Model.Notifications.Any(n => n.Date.Day.Equals(date.Day) && n.Date.Month.Equals(date.Month) && n.Date.Year.Equals(date.Year)))
                                {
                                    <span class="badge badge-pill badge-info ml-1">
                                        @Model.Notifications.Count(n => n.Date.Day.Equals(date.Day))
                                    </span>
                                }
                            </div>
                        </td>
                        @if (i == 7)
                        {
                            i = 0;
                        @:</tr><tr>
                        }
                        i++;
                    }
            </tbody>
        </table>
    </div>
</div>

Calendar/Pages/Calendar/Notification.cshtml
@page
@model NotificationModel
@{
}
@{
    var i = 1;
    int routeLastMonth;
    int routeLastYear;
    if (Model.Month == 1)
    {
        routeLastYear = Model.Year - 1;
        routeLastMonth = 12;
    }
    else
    {
        routeLastMonth = Model.Month - 1;
        routeLastYear = Model.Year;
    }
    int routeNextMonth;
    int routeNextYear;
    if (Model.Month == 12)
    {
        routeNextYear = Model.Year + 1;
        routeNextMonth = 1;
    }
    else
    {
        routeNextMonth = Model.Month + 1;
        routeNextYear = Model.Year;
    }
}
<link rel="stylesheet" href="~/css/calendar/index.css" />
<div class="d-flex justify-content-center">
    <div class="w-50 d-flex flex-column">
        <div class="d-flex justify-content-around mb-2">
            <a asp-route-year="@routeLastYear" asp-route-month="@routeLastMonth" asp-route-day="@Model.Day"><button type="button" class="btn btn-primary">Last month</button></a>
            <h1>@Model.Year @Model.GetMonthName()</h1>
            <a asp-route-year="@routeNextYear" asp-route-month="@routeNextMonth" asp-route-day="@Model.Day"><button type="button" class="btn btn-primary">Next month</button></a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Mo</th>
                    <th scope="col" class="text-center">Tu</th>
                    <th scope="col" class="text-center">We</th>
                    <th scope="col" class="text-center">Th</th>
                    <th scope="col" class="text-center">Fr</th>
                    <th scope="col" class="text-center">St</th>
                    <th scope="col" class="text-center">Su</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    @foreach (var date in Model.Calendar)
                    {
                        <td class="text-center" @(date.Day == Model.Day && date.Month == Model.Month ? "style=background-color:blueviolet" : "")>
                            <div class="d-flex justify-content-right" @(date.Month != Model.Month ? "style=color:gray" : "")>
                                <a class="link" asp-page="Notification" asp-route-year="@date.Year" asp-route-month="@date.Month" asp-route-day="@date.Day">
                                    @date.Day
                                </a>
                                @if (Model.Notifications.Any(n => n.Date.Day.Equals(date.Day) && n.Date.Month.Equals(date.Month) && n.Date.Year.Equals(date.Year)))
                                {
                                    <span class="badge badge-pill badge-info ml-1">
                                        @Model.Notifications.Count(n => n.Date.Day.Equals(date.Day))
                                    </span>
                                }
                            </div>
                        </td>
                        @if (i == 7)
                        {
                            i = 0;
                        @:</tr><tr>
                        }
                        i++;
                    }
            </tbody>
        </table>
    </div>
</div>
<div class="d-flex flex-wrap">
    @foreach (var notificate in Model.DayNotifications)
    {
        <div class="card text-white bg-primary m-3" style="max-width: 20rem; min-width: 10rem;">
            <div class="card-header d-flex justify-content-between">
                <div>Notification</div>
                <form method="post">
                    <input type="submit" class="btn btn-danger btn-sm" asp-page-handler="Delete" asp-route-notificationId="@notificate.Id" asp-route-year="@Model.Year" asp-route-month="@Model.Month" asp-route-day="@Model.Day" value="x">
                </form>
            </div>
            <div class="card-body">
                <h4 class="card-title">@notificate.Date.ToString("MM/dd/yy H:mm")</h4>
                <p class="card-text">@notificate.Description</p>
            </div>
        </div>
    }
</div>
<div class="d-flex justify-content-center">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="NotificationViewModel.Hours" class="control-label">Hours</label>
            <select asp-for="NotificationViewModel.Hours" class="form-control" asp-items="ViewBag.TeacherId">
                @for (int hour = 0; hour <= 24; hour++)
                {
                    <option>@hour</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label asp-for="NotificationViewModel.Minutes" class="control-label">Minutes</label>
            <select asp-for="NotificationViewModel.Minutes" class="form-control" asp-items="ViewBag.TeacherId">
                @for (int minute = 0; minute <= 60; minute += 5)
                {
                    <option>@minute</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label asp-for="NotificationViewModel.Description" class="control-label">Description</label>
            <input type="text" step="300" asp-for="NotificationViewModel.Description" class="form-control"></input>
        </div>
        <div class="form-group">
            <input type="submit" asp-page-handler="Create" asp-route-year="@Model.Year" asp-route-month="@Model.Month" asp-route-day="@Model.Day" value="Create" class="btn btn-primary" />
        </div>
    </form>
</div>